-- Register all ZenProfessions professions
CharacterProfession.register("zen:journalist")
CharacterProfession.register("zen:minister")
CharacterProfession.register("zen:dj")
CharacterProfession.register("zen:vcrotechnician")
CharacterProfession.register("zen:arcadetechnician")
CharacterProfession.register("zen:switchboardoperator")
CharacterProfession.register("zen:secretary")
CharacterProfession.register("zen:postman")
CharacterProfession.register("zen:busdriver")
CharacterProfession.register("zen:cabdriver")
CharacterProfession.register("zen:janitor")
CharacterProfession.register("zen:photographer")
CharacterProfession.register("zen:videorentalclerk")
CharacterProfession.register("zen:plumber")
CharacterProfession.register("zen:teacher")
CharacterProfession.register("zen:baker")
CharacterProfession.register("zen:hunter")
CharacterProfession.register("zen:lifeguard")
CharacterProfession.register("zen:paramedic")

-- Register all ZenProfessions traits
CharacterTrait.register("zen:investigative")
CharacterTrait.register("zen:spiritual")
CharacterTrait.register("zen:electronicspecialist")
CharacterTrait.register("zen:techsavvy")
CharacterTrait.register("zen:mechanicspecialist")
CharacterTrait.register("zen:communications")
CharacterTrait.register("zen:organized")
CharacterTrait.register("zen:deliveryexpert")
CharacterTrait.register("zen:roadsavvy")
CharacterTrait.register("zen:maintenancepro")
CharacterTrait.register("zen:marksman")
CharacterTrait.register("zen:entertainmentbuff")
CharacterTrait.register("zen:leakrepair")
CharacterTrait.register("zen:educator")
CharacterTrait.register("zen:culinaryartist")
CharacterTrait.register("zen:tracker")
CharacterTrait.register("zen:swimmer")
CharacterTrait.register("zen:firstresponder")

-- Register nature-based professions
CharacterProfession.register("zen:botanist")
CharacterProfession.register("zen:parkranger")
CharacterProfession.register("zen:geologist")
CharacterProfession.register("zen:beekeeper")
CharacterProfession.register("zen:forestfirefighter")
CharacterProfession.register("zen:wildlifebiologist")
CharacterProfession.register("zen:horticulturist")
CharacterProfession.register("zen:lumberjack")
CharacterProfession.register("zen:wildernessguide")
CharacterProfession.register("zen:meteorologist")

-- Register nature-based traits
CharacterTrait.register("zen:naturalist")
CharacterTrait.register("zen:wildlifekeeper")
CharacterTrait.register("zen:earthreader")
CharacterTrait.register("zen:apiarist")
CharacterTrait.register("zen:firestopper")
CharacterTrait.register("zen:fieldresearcher")
CharacterTrait.register("zen:greenthumb")
CharacterTrait.register("zen:timberman")
CharacterTrait.register("zen:trailblazer")
CharacterTrait.register("zen:stormchaser")